version: 3

tasks:
  run:main:
    cmds:
      - go run main.go
    env:
      DATABASE_URL: postgresql://postgres:Wc3tbviBivzEQVFO8ueg@containers-us-west-79.railway.app:6340/railway

  run:dev:
    cmds:
      - go run main.go
    env:
      DATABASE_URL: postgresql://postgres:0S9ykfJ9Vq3UfhxzEAP1@containers-us-west-64.railway.app:5913/railway

  test:
    desc: Runs go tests
    cmds:
      - go test -race  ./...

  test-coverage:
      desc: Runs go tests and calculates test coverage
      cmds:
        - go test -race -coverprofile=c.out ./...
