// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuthorizerEmailTemplates       string
	AuthorizerEnvs                 string
	AuthorizerOtps                 string
	AuthorizerSessions             string
	AuthorizerUsers                string
	AuthorizerVerificationRequests string
	AuthorizerWebhookLogs          string
	AuthorizerWebhooks             string
	Tenants                        string
}{
	AuthorizerEmailTemplates:       "authorizer_email_templates",
	AuthorizerEnvs:                 "authorizer_envs",
	AuthorizerOtps:                 "authorizer_otps",
	AuthorizerSessions:             "authorizer_sessions",
	AuthorizerUsers:                "authorizer_users",
	AuthorizerVerificationRequests: "authorizer_verification_requests",
	AuthorizerWebhookLogs:          "authorizer_webhook_logs",
	AuthorizerWebhooks:             "authorizer_webhooks",
	Tenants:                        "tenants",
}
